# Generated by Django 5.1.5 on 2025-01-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_user_name', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=32)),
                ('ssh_public_key', models.CharField(max_length=512, null=True)),
                ('ssh_password', models.CharField(max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Server Connection Configuration',
                'verbose_name_plural': 'Server Connection Configurations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=32)),
                ('is_included', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_config', to=settings.AUTH_USER_MODEL)),
                ('server_connection_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_config', to='SCS.serverconnectionconfig')),
            ],
            options={
                'verbose_name': 'Server Configuration',
                'verbose_name_plural': 'Server Configurations',
                'ordering': ['server_name'],
            },
        ),
    ]
